site_name: The Gulag Archipelago Audiobook Information
site_description: Information and metadata about The Gulag Archipelago Audiobook by Aleksandr Solzhenitsyn
site_author: Bhavesh Sooka
site_url: https://bhaveshsooka.github.io/the-gulag-archipelago-info
repo_url: https://github.com/bhaveshsooka/the-gulag-archipelago-info
nav:
  - ...
theme: 
  name: torillic
  background_image: img/background-img.jpg
plugins:
  - awesome-pages
  - search
  - macros