site_name: The Gulag Archipelago Audiobook Information
site_description: Information and metadata about The Gulag Archipelago Audiobook by Aleksandr Solzhenitsyn
site_author: Bhavesh Sooka
site_url: https://bhaveshsooka.github.io/the-gulag-archipelago-info
repo_url: https://github.com/bhaveshsooka/the-gulag-archipelago-info
nav:
  - Home: index.md
  - ...
  - About: about/index.md
theme:
  name: null
  custom_dir: custom_theme/
  favicon: img/favicon.ico
plugins:
  - awesome-pages
  - macros
custom_metadata:
  youtube_playlist: https://youtube.com/playlist?list=PLwt9OUJ1gdC8wPFUW4qcYdKv4q3G6CEmk
